services:
  db:
    image: postgres:16.4
    restart: always
    ports:
      - '${DB_PORT}:${DB_PORT}'
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGTZ: 'America/Mexico_City'
    container_name: ${CONTAINER_NAME}
    volumes:
      - ./postgres:/var/lib/postgresql/data
      - ./backup:/var/lib/postgresql/backup
      # - '/etc/localtime:/etc/localtime:ro'
      # - '/etc/timezone:/etc/timezone:ro'
    command: -p ${DB_PORT}